---
transport:
  name: winrm
  username: Administrator
  password: <%= ENV['vmpassword'] %>

provisioner:
    name: dsc
    dsc_local_configuration_manager_version: wmf5
    dsc_local_configuration_manager:
      reboot_if_needed: true
    configuration_script_folder: SharedDscConfig/examples
    configuration_script: Default.ps1

verifier:
  name: pester
  test_folder: SharedDscConfig/Validation

platforms:
  - name: 2012r2_WMF5
    os_type: windows
    shell: powershell
    transport:
      name: winrm
  - name: Win2016
    os_type: windows
    shell: powershell
    transport:
      name: winrm

suites:
  - name: Default
  - name: OtherTestSuite