#
# Module manifest for module 'SharedDscConfig'
#
# Generated by: Gael
#
# Generated on: 08/06/2017
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'JeaConfig.schema.psm1'

# Version number of this module.
ModuleVersion = '0.0.1'

# ID used to uniquely identify this module
GUID = '39c949d5-fae3-499b-9edf-674865ad37a4'

# Author of this module
Author = 'Chris Gardner'

# Company or vendor of this module
CompanyName = ''

# Copyright statement for this module
Copyright = '(c) 2017 Chris. All rights reserved.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @('JeaDsc')

# DSC resources to export from this module
DscResourcesToExport = @('JeaConfig')

}

